### ISSUE TITLE
Build foliage binaries

### ISSUE THREAD

**Issue by yvan-sraka** [input-output-hk/foliage#62]
We should have prebuilt foliage binaries readily available for developers to download.

On GitHub I had a GHA CI that, on release tag, builds exes for linux, macos, and windows and adds them to the releage page.
I later disabled it and focused on doing everything with nix instead. It's still there and could be revived.
https://github.com/andreabedini/foliage/blob/main/.github/workflows/haskell.yml

On hydra, I have foliage binaries built for [aarch64-darwin](https://ci.zw3rk.com/build/2145001), [aarch64-linux](https://ci.zw3rk.com/build/2145004), [x86_64-darwin](https://ci.zw3rk.com/build/2144998), [x86_64-linux](https://ci.zw3rk.com/build/2144994), and also [x86_64-linux-musl](https://ci.zw3rk.com/build/2145010).

I never managed to get aarch64-linux-musl to work. I haven't tried windows.

See https://github.com/andreabedini/foliage/blob/main/flake.nix

**Comment by michaelpj** [comment]
Alternatively: publish to Hackage and tell people to install it with `cabal`?

**Comment by andreabedini** [comment]
@yvan-sraka The CI doesn't seem to be working, can you have a look?

**Comment by yvan-sraka** [comment]
> @yvan-sraka The CI doesn't seem to be working, can you have a look?

I quickly iterate on it here https://github.com/input-output-hk/foliage/pull/67, it's now trigger only on new tags pushed, so I should probably test it in a fork :)

**Comment by andreabedini** [comment]
If you make it create draft releases, we can just test it and then delete the release.
